// src/redux/userSlice.js
import { createSlice } from '@reduxjs/toolkit';
import axios from 'axios';

const initialState = {
  user: {
    first_name: '',
    last_name: '',
    username: '',
  },
  points: 0,
};

const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setUser(state, action) {
      state.user = action.payload;
    },
    setPoints(state, action) {
      state.points = action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { setUser, setPoints } = userSlice.actions;

// Thunk for fetching user data
export const fetchUserData = (telegramId) => async (dispatch) => {
  try {
    const response = await axios.get(`http://localhost:5001/api/users/${telegramId}`);
    const { points, firstName, lastName, username } = response.data;

    // Dispatch actions to update the Redux store
    dispatch(setUser({ first_name: firstName, last_name: lastName, username }));
    dispatch(setPoints(points));
  } catch (error) {
    console.error('Error fetching user data:', error);
  }
};

// Export the reducer for the slice
export default userSlice.reducer;